CREATE TABLE `inference` (
  `IDX` int(11) NOT NULL AUTO_INCREMENT,
  `REQUEST_ID` varchar(255) DEFAULT NULL,
  `PROCESS_TIME` datetime DEFAULT current_timestamp(),
  `FILE_PATH` varchar(255) DEFAULT NULL,
  `RESULT_DATA` text DEFAULT NULL,
  `RUNTIME` double DEFAULT NULL,
  PRIMARY KEY (`IDX`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='추론';